### ISSUE TITLE
能否启动项root=LABEL=ROOTFS_EMMC

### ISSUE THREAD

**Issue by xiayang0521** [7Ji/amlogic-s9xxx-archlinuxarm#10]
新版系统ArchLinuxARM-aarch64-Amlogic-20230225_150037-root.tar.xz已在B860-AV3.2M (CPU: S905L3A) 测试，测试启动以及pacman安装软件没问题。
有个问题，Kernel command line 能否把改用LABEL， 比如，root=LABEL=ROOTFS_EMMC，同时在fstab里也都改用LABEL。

**Comment by 7Ji** [comment]
Label 多个安装间会重复的，同时插多个U盘/sd的时候挂载会混。uuid至少在不同发布里是唯一的。

**Comment by 7Ji** [comment]
而且你是觉得编辑fstab麻烦吗？更新fstab本来也不应该是手操的，arch有`genfstab`这个工具。/boot下的配置也就是一行blkid /dev/xxx | cut -d '"' -f 2，重定向到配置文件里再vim改或者直接粘贴进去
