### ISSUE TITLE
能写入emmc吗 

### ISSUE THREAD

**Issue by Heisenberg5201314** [7Ji/amlogic-s9xxx-archlinuxarm#12]
能写入emmc吗 armbian可以通过armbian-install直接写入emmc 我是直接用的烧录的镜像直接烧录到u盘 现在想把系统写进emmc 但是教程好像没有写入emmc的操作 是我遗漏了吗

**Comment by 7Ji** [comment]
https://7ji.github.io/embedded/2022/11/08/alarm-install.html

**Comment by 7Ji** [comment]
不提供安装脚本，因为预定义的安装脚本在事实上限制了安装布局，自己分区格式化可以做到各种不同的布局。安装本身也就分区+格式化+复制文件，已经是几个最简操作，再搞个脚本封装反而失去了灵活性。

**Comment by LoongArum** [comment]
大佬，请问您是怎么学习这方面的知识的呀，你的博客讲的很好，我也想构建自己的armlinux发行版，但是现在我对于arm架构下操作系统的底层还不太熟悉，看了您的博客也只是对分区和启动流程有了一定的认知，望大佬指点!
