### ISSUE TITLE
是否能做成emmc线刷包，直接使用USB Burning Tool进行安装

### ISSUE THREAD

**Issue by a520ass** [7Ji/amlogic-s9xxx-archlinuxarm#15]
大佬，这个能直接做成线刷包吗，类似这个的
https://dl.khadas.com/products/vim1/firmware/ubuntu/
![image](https://user-images.githubusercontent.com/8427401/233821443-677558f6-5c58-4c17-a88d-d3733cad323c.png)

**Comment by 7Ji** [comment]
这里面镜像用的都是aml的原厂内核，非主线。

这个项目用的是主线内核，如果启用我的对于aml格式分区表的支持的话（这里的内核已经启用），倒也可以做成线刷，但是那样的话镜像的适配单位是板子。这个项目，我只想分发一个通用镜像。

而且，要打成线刷，就不能用主线u-boot，这个的牺牲就很不值得了，Amlogic的u-boot版本老得要死，还和主流启动方案不兼容。

**Comment by a520ass** [comment]
> 这里面镜像用的都是aml的原厂内核，非主线。
> 
> 这个项目用的是主线内核，如果启用我的对于aml格式分区表的支持的话（这里的内核已经启用），倒也可以做成线刷，但是那样的话镜像的适配单位是板子。这个项目，我只想分发一个通用镜像。
> 
> 而且，要打成线刷，就不能用主线u-boot，这个的牺牲就很不值得了，Amlogic的u-boot版本老得要死，还和主流启动方案不兼容。

嗯，非主线就算了，我以为它这个是主线u-boot，主线内核
