### ISSUE TITLE
Front display doesn't work as it should, or sound, or WiFi

### ISSUE THREAD

**Issue by LupusEtFlos** [7Ji/amlogic-s9xxx-archlinuxarm#23]
All it displays is "boot", how would I go about showing the time and such on it? As for sound, it says I got a "dummy output", and at least through HDMI I have no sound whatsoever.  I've got an S905W, TX3 Mini.

**Comment by 7Ji** [comment]
For front display, ensure `openvfd` module is available, then ensure `/openvfd` node exists in your device tree, basically follow https://github.com/7Ji/YAopenvfD?tab=readme-ov-file#kernel-dependency , then start `YAopenvfD-updater.service` and optionally enable autostart following https://github.com/7Ji/YAopenvfD?tab=readme-ov-file#systemd-integration
