### ISSUE TITLE
mibox3安装alarm，通过u盘启动使用密码root和alarm无法登录

### ISSUE THREAD

**Issue by xxmdd** [7Ji/amlogic-s9xxx-archlinuxarm#25]
mibox3（MDZ-16-AA）我尝试过armbian，使用你的uboot和自己编译你的mibox3.dtb能够正常启动，但是我尝试过很多方法，无法写入emmc，现在想使用[amlogic-s9xxx-archlinuxarm]，我想通过你dump的img通过dd导入，也是应该要通过U盘启动进alarm才行吧，我登录alarm时用户名root密码root和用户名alarm密码alarm无法登录，能否提供一下默认密码，十分感谢；
我对alarm的dd写入emmc也不是很熟悉，请问有没用操作方法，或者是我通过u盘直接写入[amlogic-s9xxx-archlinuxarm]镜像文件也可以吧？

**Comment by 7Ji** [comment]
https://github.com/7Ji/amlogic-s9xxx-archlinuxarm?tab=readme-ov-file#users

**Comment by pragandsensdiary** [comment]
get ready to learn chinese buddy
