### ISSUE TITLE
安装到emmc文档链接能贴在readme里面吗？

### ISSUE THREAD

**Issue by frankiezdh** [7Ji/amlogic-s9xxx-archlinuxarm#26]
Installing on USB drive is more recommended, and then [alarm-install][alarm guide on blog] can be referred to to install to eMMC or to another USB drive/SD card in the ArchLinux way

看起来链接没有

**Comment by 7Ji** [comment]
https://7ji.github.io/embedded/2022/11/11/amlogic-booting.html

**Comment by 7Ji** [comment]
Closed by https://github.com/7Ji/amlogic-s9xxx-archlinuxarm/commit/15381485711d5d5bfdae40758afe88beb1fde48c
